version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  mongo:
    image: mongo
    ports:
      - 27017:27017
  coreConfigService:
    image: symbiote/coreconfigservice
    ports:
      - 8888:8888
    volumes:
      - ../CoreConfigProperties:/CoreConfigProperties
  eurekaService:
    image: symbiote/eurekaservice
    ports:
      - 8761:8761
    links:
      - coreConfigService
  zipkinService:
    image: symbiote/zipkinservice
    ports:
      - 8762:8762
    links:
      - coreConfigService
      - eurekaService
  # administration:
  #   image: symbiote/administration
  #   ports:
  #     - 8250:8250
  #   links:
  #     - coreConfigService
  #     - eurekaService
  cloudCoreInterface:
    image: symbiote/cloudcoreinterface
    ports:
      - 8101:8101
    links:
      - coreConfigService
      - eurekaService
  coreInterface:
    image: symbiote/coreinterface
    ports:
      - 8100:8100
    links:
      - coreConfigService
      - eurekaService
  registry:
    image: symbiote/registry
    ports:
      - 8200:8200
    links:
      - coreConfigService
      - eurekaService
  coreresourceaccessmonitor:
    image: symbiote/coreresourceaccessmonitor
    ports:
      - 8310:8310
    links:
      - coreConfigService
      - eurekaService
  search:
    image: symbiote/search
    ports:
      - 8120:8120
    volumes:
      - ./build/jena:/root/coreSearchTriplestore
    links:
      - coreConfigService
      - eurekaService
