version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
  mongo:
    image: mongo
    ports:
      - 27017:27017
  coreConfigService:
    image: symbiote/coreconfigservice
    ports:
      - 8888:8888
    volumes:
      - ../CoreConfigProperties:/CoreConfigProperties
  eurekaService:
    image: symbiote/eurekaservice
    ports:
      - 8761:8761
      - 8080:8080
    links:
      - coreConfigService
