version: "3.5"

x-environment:
  &default-environment
  #### Uncomment and configure the following if you are behind a proxy
  #  - JAVA_HTTP_PROXY=-Dhttp.proxyHost=TODO -Dhttp.proxyPort=TODO
  #  - JAVA_HTTPS_PROXY=-Dhttps.proxyHost=TODO -Dhttps.proxyPort=TODO
  #  - JAVA_SOCKS_PROXY=-DsocksProxyHost=TODO -DsocksProxyPort=TODO
  #  - JAVA_NON_PROXY_HOSTS=-Dhttp.nonProxyHosts=*symbiote-h2020.eu|symbiote-coreconfig|symbiote-aam|symbiote-eureka
  - _JAVA_OPTIONS=$JAVA_HTTP_PROXY $JAVA_HTTPS_PROXY $JAVA_NON_PROXY_HOSTS -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1
#  - _JAVA_OPTIONS=$JAVA_HTTP_PROXY
services:
  symbiote-rabbitmq:
    image: rabbitmq:3-alpine
    networks:
      - symbiote
    ports:
      - 5671:5671
      - 5672:5672
  symbiote-mongo:
    image: mongo:3.6
    networks:
      - symbiote
    volumes:
      - symbiote-core-vol:/data/db
  symbiote-coreconfig:
    environment: *default-environment
    image: symbioteh2020/symbiote-coreconfig:3.0.5
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - symbiote
    volumes:
      - symbiote-vol-config:/home/CoreConfigProperties
    ports:
      - 8888:8888
  symbiote-aam:
    environment: *default-environment
    image: symbioteh2020/symbiote-aam:5.0.12
    depends_on:
      - symbiote-rabbitmq
      - symbiote-mongo
      - symbiote-coreconfig
    deploy:
      resources:
        limits:
          memory: 1000M
    networks:
      - symbiote
    secrets:
      - source: aambootstrapconfig
        target: /home/bootstrap.properties
      - source: aamkeystore
        target: /home/core.p12
  symbiote-eureka:
    environment: *default-environment
    image: symbioteh2020/symbiote-eureka:3.0.2
    deploy:
      resources:
        limits:
          memory: 400M
    networks:
      - symbiote
    ports:
      - 8761:8761
    secrets:
      - source: eurekaconfig
        target: /home/bootstrap.properties
  symbiote-admin:
    environment: *default-environment
    image: symbioteh2020/symbiote-admin:3.1.6
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - symbiote
    secrets:
      - source: adminconfig
        target: /home/bootstrap.properties
  symbiote-coreinterface:
    environment: *default-environment
    image: symbioteh2020/symbiote-coreinterface:3.0.3
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: ciconfig
        target: /home/bootstrap.properties
  symbiote-cloudcoreinterface:
    environment: *default-environment
    image: symbioteh2020/symbiote-cloudcoreinterface:3.0.3
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: cciconfig
        target: /home/bootstrap.properties
  symbiote-cram:
    environment: *default-environment
    image: symbioteh2020/symbiote-cram:3.0.6
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: cramconfig
        target: /home/bootstrap.properties
  symbiote-crm:
    environment: *default-environment
    image: symbioteh2020/symbiote-crm:3.0.2
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: crmconfig
        target: /home/bootstrap.properties
  symbiote-registry:
    environment: *default-environment
    image: symbioteh2020/symbiote-registry:3.0.4
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: registryconfig
        target: /home/bootstrap.properties
  symbiote-search:
    environment: *default-environment
    image: symbioteh2020/symbiote-search:3.0.13
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    volumes:
      - symbiote-search-triplestore:/home/coreSearchTriplestore
    secrets:
      - source: searchconfig
        target: /home/bootstrap.properties
  symbiote-semanticmanager:
    environment: *default-environment
    image: symbioteh2020/symbiote-semanticmanager:3.0.3
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: smconfig
        target: /home/bootstrap.properties
  symbiote-bt:
    environment: *default-environment
    image: symbioteh2020/symbiote-bt:3.0.5
    command: sh -c 'java -DSPRING_BOOT_WAIT_FOR_SERVICES=symbiote-coreinterface:8100 -Xmx1024m -Duser.home=/home -Dspring.output.ansi.enabled=NEVER -jar $$(ls *run.jar)'
    depends_on:
      - symbiote-aam
    deploy:
      resources:
        limits:
          memory: 1024M
    networks:
      - symbiote
    secrets:
      - source: btconfig
        target: /home/bootstrap.properties

networks:
  symbiote:
    name: symbiote
volumes:
  symbiote-vol-config:
  symbiote-core-vol:
  symbiote-search-triplestore:
secrets:
  eurekaconfig:
    file: ./configuration/bootstrap.properties
  aambootstrapconfig:
    file: ./configuration/AuthenticationAuthorizationManager/bootstrap.properties
  aamkeystore:
    file: ./configuration/core.p12
  adminconfig:
    file: ./configuration/bootstrap.properties
  ciconfig:
    file: ./configuration/CoreInterface/bootstrap.properties
  cciconfig:
    file: ./configuration/bootstrap.properties
  cramconfig:
    file: ./configuration/bootstrap.properties
  crmconfig:
    file: ./configuration/bootstrap.properties
  registryconfig:
    file: ./configuration/bootstrap.properties
  searchconfig:
    file: ./configuration/bootstrap.properties
  smconfig:
    file: ./configuration/bootstrap.properties
  btconfig:
    file: ./configuration/bootstrap.properties
